# Resolve react_native_pods.rb with node to allow for hoisting
# (원래 있던 require 줄 대신 node_require 유틸을 정의하고 사용)
def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# require both react-native's and react-native-permissions scripts
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

# ⚠️ 아래에서 사용하고 싶은 권한만 선택해서 넣어라
# Notifications 권한(푸시)만 필요하므로 'Notifications' 넣음
setup_permissions([
  'Notifications',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'papayasns' do
  config = use_native_modules!

  # 🔥 Firebase 관련 pod들만 모듈 헤더 활성화
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true   # FCM

  # ✅ Firebase Messaging (FCM) 네이티브 Pod
  pod 'Firebase/Messaging', :modular_headers => true

  # 🗺️ Google Maps
  pod 'react-native-maps', :path => '../node_modules/react-native-maps', :subspecs => ['Google', 'Maps']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end
